routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});
Route::get('protected', ['middleware' => ['admin'], function() {
    return "this page requires that you be logged in and an Admin";
}]);


Auth::routes();

Route::get('/contacts', function () {
    return view('pages.contact');
})->name('contacts');

Route::get('/home', 'HomeController@index');

Route::resource('/dishes', 'DishesController');



Route::resource('reservations', 'ReservationController');

Route::get('/orders/store', 'OrdersController@store')->name('orders.store');

Route::get('/orders/order', 'OrdersController@order')->name('orders.order');

Route::resource('orders', 'OrdersController');


Route::group(['middleware' => 'auth'], function()
{
    Route::get('/profile', 'ProfilesController@profile')->name('user.profile');
    Route::patch('/profile/{id}',  'ProfilesController@update')->name('user.update');
    Route::post('/cart/add/{dishId}', 'CartController@addItem')->name('cart.add');
    Route::post('/cart/reduce/{dishId}', 'CartController@reduceItem')->name('cart.reduce');
    Route::get('/cart/remove/{dishId}', 'CartController@removeItem')->name('cart.remove');
    Route::get('/cart', 'CartController@showCart')->name('cart');

    Route::get('/dishes/destroy/{id}','DishesController@destroy')->name('dishes.destroy');





});

Route::group(['middleware' => 'auth', 'isAdmin'], function()
{
    Route::resource('/users', 'UserProfilesController');




});

resources/views/partials/_footer.blade.php
<hr>

<p class="text-center">Copyright L.K.</p>

resources/views/partials/_head.blade.php
       <!DOCTYPE html>
       <html lang="en">

       <head>

           <meta charset="utf-8">
           <meta http-equiv="X-UA-Compatible" content="IE=edge">
           <meta name="viewport" content="width=device-width, initial-scale=1">
           <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
           <title>Laravel Blog</title> <!-- CHANGE THIS TITLE FOR EACH PAGE -->
           <!-- CHANGE THIS TITLE FOR EACH PAGE -->

           <!-- Bootstrap -->
           <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

           <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
           <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
           <!--[if lt IE 9]>
           <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
           <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
           {{  Html::style('css/styles.css')}}
           <![endif]-->
       </head>

resources/views/partials/_js.blade.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

resources/views/partials/_messages.blade.php
@if (Session::has('success') )

    <div class="alert alert-success" role="alert">


        <strong>Success:</strong>

        {{ Session::get('success') }}

    </div>

@endif

@if (count($errors) > 0)

    <div class="alert alert-danger" role="alert">

        <strong> Error:</strong>
        <ul>
        @foreach ($errors->all() as $error)

            <li>{{ $error }}</li>

        @endforeach
        </ul>
    </div>

@endif

resources/views/partials/_nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{route('dishes.index')}}">Dishes Menu</a></li>
                @if(Auth::check() && Auth::user()->isAdmin())
                    <li><a href="{{route('reservations.index')}}">Table reservation</a></li>

                @else
                    <li><a href="{{route('reservations.create')}}">Table reservation</a></li>
                @endif
                <li><a href="{{route('contacts')}}">Contacts</a></li>
                @if (Auth::check()) <li><a href="{{route('user.profile')}}"> User profile </a></li> @endif
                @if (Auth::check() && Auth::user()->isAdmin()) <li><a href="{{route('users.index')}}"> Users list</a></li> @endif
                @if (Auth::check() && Auth::user()->isAdmin()) <li><a href="{{route('orders.index')}}"> Orders </a></li> @endif
                @if (Auth::check()) <li><a href="{{route('orders.order')}}"> My orders</a></li> @endif

            </ul>

            @if (Auth::check())
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <li><a href="{{route('cart')}}">Shopping cart
                            <span class="badge"></span>
                        </a></li>

                            <li><a href="{{ url('/') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>

                    </li>


            @endif

                    @if (!Auth::check())
                    <ul class="nav navbar-nav navbar-right">


                    <li><a href="/login">Login</a></li>
                    <li><a href="/register">Register</a></li>



                </ul>
                    @endif


            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

resources/views/partials/head.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Laravel Blog</title> <!-- CHANGE THIS TITLE FOR EACH PAGE -->
    <!-- CHANGE THIS TITLE FOR EACH PAGE -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="{{asset('css/app.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('css/styles.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{asset('css/font-awesome.css')}}" rel="stylesheet" type="text/css"/>
</head>