routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('pages.welcome');
});
Route::get('protected', ['middleware' => ['admin'], function() {
    return "this page requires that you be logged in and an Admin";
}]);


Auth::routes();

Route::get('/contacts', function () {
    return view('pages.contact');
})->name('contacts');

Route::get('/home', 'HomeController@index');

Route::resource('/dishes', 'DishesController');



Route::resource('reservations', 'ReservationController');

Route::get('/orders/store', 'OrdersController@store')->name('orders.store');

Route::get('/orders/order', 'OrdersController@order')->name('orders.order');

Route::resource('orders', 'OrdersController');


Route::group(['middleware' => 'auth'], function()
{
    Route::get('/profile', 'ProfilesController@profile')->name('user.profile');
    Route::patch('/profile/{id}',  'ProfilesController@update')->name('user.update');
    Route::post('/cart/add/{dishId}', 'CartController@addItem')->name('cart.add');
    Route::post('/cart/reduce/{dishId}', 'CartController@reduceItem')->name('cart.reduce');
    Route::get('/cart/remove/{dishId}', 'CartController@removeItem')->name('cart.remove');
    Route::get('/cart', 'CartController@showCart')->name('cart');

    Route::get('/dishes/destroy/{id}','DishesController@destroy')->name('dishes.destroy');





});

Route::group(['middleware' => 'auth', 'isAdmin'], function()
{
    Route::resource('/users', 'UserProfilesController');




});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','surname','country','address','city','zip_code', 'telephone', 'date',  'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getFullName () {


        return trim( $this->name . " " . $this->surname);


}

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'user_roles', 'user_id', 'role_id');
    }

    public function isAdmin()
    {
        return $this->roles->contains('name', "Admin");
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

}

resources/views/users/edit.blade.php
@extends('main')

@section('content')
    @if (Auth::check() && Auth::user()->isAdmin())

    <div class="row">
    <div class=" col-md-8">
        {!!Form::model($profile, ['route' => ['users.update', $profile->id], 'method' => 'PATCH']) !!}

        {{ Form::label('name', "Name:") }}
        {{ Form::text('name',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('surname', "Surname:") }}
        {{ Form::text('surname',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('country', "Country:") }}
        {{ Form::select('country',array('Lithuania' => 'Lithuania', 'Latvia' => 'Latvia', 'Estonia' => 'Estonia' ), array('class' => 'form-control')) }}
        {{ Form::label('address', "Address:") }}
        {{ Form::text('address',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('city', "City:") }}
        {{ Form::text('city',null , array('class' => 'form-control form-group')) }}
        {{ Form::label('zip_code', "Zip code:") }}
        {{ Form::text('zip_code',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('email', "Email address:") }}
        {{ Form::text('email',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('telephone', "Telephone number:") }}
        {{ Form::text('telephone',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('date', "Date of birth:") }}
        {{ Form::date('date',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('password', "New Password:") }}
        {{ Form::password('password',null, array('class' => 'form-control form-group')) }}
        {{ Form::label('password_confirmation', "Confirm Password:") }}
        {{ Form::password('password_confirmation',null, array('class' => 'form-control form-group')) }}

        {{Form::submit('update your profile', array('class'=> 'btn btn-success btn-lg btn-block', 'style' => 'margin-top:20px'))}}
</div>





        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at: </dt>
                    <dd> {{ date('M j, Y, H:i', strtotime($profile->created_at)) }}</dd>
                </dl>
                <dl class="dl-horizontal">
                    <dt>Last updated: </dt>
                    <dd> {{ date('M j, Y, H:i', strtotime($profile->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        {!! Html::linkRoute('users.show', 'Cancel', array($profile->id), array('class'=>"btn btn-danger btn-block")) !!}

                    </div>
                    <div class="col-sm-6">
                        {{ Form::submit('Save changes', ['class' => 'btn btn-success btn-block' ]) }}


                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>

    @endif




@endsection

resources/views/users/index.blade.php
@extends('main')


@section('content')
    @if (Auth::check() && Auth::user()->isAdmin())

    <div class="row">
        <div class="col-md-10">
            <h1>All profiles</h1>
        </div>


        <hr>
    </div>

    <div class="class=row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <th>#</th>
                    <th>name</th>
                    <th>surname</th>
                    <th>Adsress</th>
                    <th>date of birth</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Zip code</th>
                    <td>Email address</td>
                    <td></td>
                </thead>
                <tbody>
                @foreach($profiles as $profile)

                    <tr>
                        <th>{{$profile->id}}</th>
                        <td>{{$profile->name}}</td>
                        <td>{{$profile->surname}}</td>
                        <td>{{$profile->address}}</td>
                        <td>{{$profile->date}}</td>
                        <td>{{$profile->city}}</td>
                        <td>{{$profile->country}}</td>
                        <td>{{$profile->zip_code}}</td>
                        <td>{{$profile->email}}</td>

                        <td>{{date( 'M j, Y', strtotime($profile->created_at)) }}</td>
                        <td><a href="{{ route('users.edit', $profile->id) }}"class="btn btn-default btn-sm">edit</a></td>
                    </tr>


                 @endforeach

                </tbody>
            </table>
        </div>
    </div>

    @endif


@endsection

resources/views/users/show.blade.php
@extends('main')



@section('content')

    @if (Auth::check() && Auth::user()->isAdmin())
    <div class="row">
    <div class="col-md-8">>
    <h1>  {{ $profile->title }}</h1>

    <p class="lead">{{$profile->name}}</p>
        <p class="lead">{{$profile->phone_number}}</p>
        <p class="lead">{{$profile->number_of_people}}</p>
        <p class="lead">{{$profile->time}}</p>
        <p class="lead">{{$profile->date}}</p>
     </div>
        <div class="col-md-4">
            <div class="well">
               <dl class="dl-horizontal">
                   <dt>Created at: </dt>
                   <dd> {{ date('M j, Y, H:i', strtotime($profile->created_at)) }}</dd>
               </dl>
                <dl class="dl-horizontal">
                    <dt>Last updated: </dt>
                    <dd> {{ date('M j, Y, H:i', strtotime($profile->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        {!! Html::linkRoute('users.edit', 'Edit', array($profile->id), array('class'=>"btn btn-primary btn-block")) !!}

                    </div>
                    <div class="col-sm-6">
                        {!! Html::linkRoute('users.destroy', 'Delete', array($profile->id), array('class'=>"btn btn-danger btn-block")) !!}

                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>

    @if (Auth::check() && Auth::user()->isAdmin())
    @endsection